### ISSUE TITLE
jaccard_purification didn't work?

### ISSUE THREAD

**Issue by fyliule** [EdisonLeeeee/GraphGallery#13]
In cora, cora_ml, citeseer and pubmed dataset, although I used jaccard_purification in GCN, output was exactly the same as vanilla GCN.

**Comment by EdisonLeeeee** [comment]
Hi, could you specify more details? I've tested [gcn-jaccard](https://github.com/EdisonLeeeee/GraphGallery/blob/master/examples/PyTorch/gcn-jaccard.py) and it worked.

**Comment by fyliule** [comment]
> Hi, could you specify more details? I've tested [gcn-jaccard](https://github.com/EdisonLeeeee/GraphGallery/blob/master/examples/PyTorch/gcn-jaccard.py) and it worked.

Thank you. The reason is that I used the wrong API, it work.
